using System.Text;
using UpgradeAgent.Bumping;

namespace UpgradeAgent.Run;

public static class CommitMessage
{
    /// <summary>Conventional commit: short subject for up to three packages, otherwise a count with a body list.</summary>
    public static string Create(string groupName, IReadOnlyList<VersionEdit> edits, string runId)
    {
        var steps = edits
            .Select(e => (e.Id, e.From, e.To))
            .Distinct()
            .OrderBy(s => s.Id, StringComparer.OrdinalIgnoreCase)
            .ToList();

        var subject = steps.Count <= 3
            ? $"chore(deps): bump {string.Join(", ", steps.Select(s => $"{s.Id} {s.From} -> {s.To}"))}"
            : $"chore(deps): bump {steps.Count} packages ({groupName})";

        var body = new StringBuilder();
        body.AppendLine(subject).AppendLine();
        foreach (var (id, from, to) in steps)
        {
            body.AppendLine($"- {id} {from} -> {to}");
        }

        body.AppendLine().Append($"Generated by UpgradeAgent run {runId}. Build, tests and guardrails passed.");
        return body.ToString();
    }
}
