using System.Globalization;
using System.Text;
using UpgradeAgent.Detection;
using UpgradeAgent.Run;
using UpgradeAgent.Infrastructure;

namespace UpgradeAgent.Publishing;

/// <summary>Markdown for the pull request, built only from the run report (what the app verified, not what the agent claimed).</summary>
internal static class PrDescription
{
    public static string Title(RunReport report) =>
        $"chore(deps): NuGet updates {report.StartedUtc:yyyy-MM-dd} ({report.Ledger.Count} group{(report.Ledger.Count == 1 ? "" : "s")})";

    public static string Create(RunReport report)
    {
        var md = new StringBuilder();
        md.AppendLine(CultureInfo.InvariantCulture, $"# {Title(report)}").AppendLine();
        md.AppendLine(CultureInfo.InvariantCulture, $"Automated by **UpgradeAgent** (run `{report.RunId}`, branch `{report.Branch}`). Each group below was bumped, built, tested and checked by deterministic guardrails before it was committed. The agent's own claims were not trusted. **Please review before merging.**");
        md.AppendLine();

        AppendSummaryTable(md, report);
        AppendGroups(md, report);
        AppendNotIncluded(md, report);
        AppendStats(md, report);

        md.AppendLine("---").AppendLine("🤖 Generated by UpgradeAgent");
        return md.ToString();
    }

    private static void AppendSummaryTable(StringBuilder md, RunReport report)
    {
        md.AppendLine("## Summary").AppendLine();
        md.AppendLine("| Package | From | To | Bump | Status |");
        md.AppendLine("|---|---|---|---|---|");
        foreach (var update in report.Plan.Updates)
        {
            var group = report.Groups.FirstOrDefault(g => string.Equals(g.Name, update.Group, StringComparison.OrdinalIgnoreCase));
            var status = (update.Decision, group?.Status) switch
            {
                (UpdateDecision.Planned, GroupStatus.Accepted) => $"✅ included (`{group!.Commit!.ShortSha()}`)",
                (UpdateDecision.Planned, GroupStatus.Rejected) => "❌ rejected",
                (UpdateDecision.Planned, GroupStatus.Cancelled) => "⏹ cancelled",
                (UpdateDecision.Planned, GroupStatus.NothingToDo) => "➖ nothing to do",
                (UpdateDecision.Planned, _) => "⏸ not run",
                (UpdateDecision.Manual, _) => "✋ manual",
                (UpdateDecision.NeedsTfmUpgrade, _) => "⚠️ needs TFM upgrade",
                _ => "⏭ skipped",
            };
            md.AppendLine(CultureInfo.InvariantCulture, $"| {update.Id} | {update.From} | {update.To} | {update.Kind.ToString().ToLowerInvariant()} | {status} |");
        }

        md.AppendLine();
    }

    private static void AppendGroups(StringBuilder md, RunReport report)
    {
        md.AppendLine("## Changes by group").AppendLine();
        foreach (var group in report.Groups.Where(g => g.Status == GroupStatus.Accepted))
        {
            md.AppendLine(CultureInfo.InvariantCulture, $"### {group.Name} ✅ `{group.Commit!.ShortSha()}`").AppendLine();
            md.AppendLine(string.Join(", ", group.Edits.Select(e => $"{e.Id} {e.From} → {e.To}").Distinct()) + ".").AppendLine();

            if (group.Fix is not { Attempted: true })
            {
                md.AppendLine("Built and passed the tests with no code changes.").AppendLine();
            }

            foreach (var package in group.Fix?.Details?.Packages ?? [])
            {
                if (package.BreakingChanges.Count > 0)
                {
                    md.AppendLine(CultureInfo.InvariantCulture, $"**Breaking changes in {package.Id} {package.To}**");
                    foreach (var change in package.BreakingChanges)
                    {
                        md.AppendLine(CultureInfo.InvariantCulture, $"- {change}");
                    }

                    md.AppendLine();
                }

                if (package.Fixes.Count > 0)
                {
                    md.AppendLine("**Fixes applied**");
                    foreach (var fix in package.Fixes)
                    {
                        md.AppendLine(CultureInfo.InvariantCulture, $"- `{fix.File}`: {fix.Reason}");
                    }

                    md.AppendLine();
                }

                if (package.UpcomingDeprecations.Count > 0)
                {
                    md.AppendLine("**Upcoming deprecations**");
                    foreach (var item in package.UpcomingDeprecations)
                    {
                        md.AppendLine(CultureInfo.InvariantCulture, $"- {item}");
                    }

                    md.AppendLine();
                }
            }

            if (group.Fix is { Attempted: true, Details: null })
            {
                md.AppendLine("_The agent changed code but gave no structured summary; see the commit diff._").AppendLine();
            }

            if (group.BuildWarnings is { Count: > 0 } warnings)
            {
                md.AppendLine("**Build warnings after the update**");
                foreach (var warning in warnings.Take(10))
                {
                    md.AppendLine(CultureInfo.InvariantCulture, $"- {warning.Truncate(160)}");
                }

                md.AppendLine();
            }

            if (group.Guardrails is { Warnings.Count: > 0 } guardrails)
            {
                md.AppendLine("**Reviewer attention**");
                foreach (var warning in guardrails.Warnings)
                {
                    md.AppendLine(CultureInfo.InvariantCulture, $"- {warning}");
                }

                md.AppendLine();
            }

            if (group.Guardrails is { } report2)
            {
                md.AppendLine(CultureInfo.InvariantCulture, $"<details><summary>Guardrails: {report2.Checks.Count(c => c.Passed)}/{report2.Checks.Count} passed</summary>").AppendLine();
                foreach (var check in report2.Checks)
                {
                    md.AppendLine(CultureInfo.InvariantCulture, $"- {(check.Passed ? "✅" : "❌")} {check.Name}: {check.Detail}");
                }

                md.AppendLine().AppendLine("</details>").AppendLine();
            }

            if (group.Fix?.Stats is { } stats)
            {
                var replayed = group.Fix.Summary.StartsWith("replayed:", StringComparison.Ordinal) ? " (replayed from a recording)" : "";
                md.AppendLine(CultureInfo.InvariantCulture, $"<sub>Agent{replayed}: {stats.Model ?? "unknown model"} · {stats.Duration.TotalMinutes:0.0} min · {stats.ModelCalls} model calls · " +
                              $"{stats.ToolCalls} tool calls · {stats.InputTokens / 1000}k/{stats.OutputTokens / 1000}k tokens" +
                              $"{(stats.OperatorApprovals > 0 ? $" · {stats.OperatorApprovals} operator approval(s)" : "")}</sub>").AppendLine();
            }
        }
    }

    private static void AppendNotIncluded(StringBuilder md, RunReport report)
    {
        var rejected = report.Groups.Where(g => g.Status is GroupStatus.Rejected or GroupStatus.Cancelled).ToList();
        var notPlanned = report.Plan.Updates.Where(u => u.Decision != UpdateDecision.Planned).ToList();
        if (rejected.Count == 0 && notPlanned.Count == 0)
        {
            return;
        }

        md.AppendLine("## Not included").AppendLine();
        foreach (var group in rejected)
        {
            md.AppendLine(CultureInfo.InvariantCulture, $"- ❌ **{group.Name}** ({string.Join(", ", group.Edits.Select(e => $"{e.Id} {e.From} → {e.To}").Distinct())}): {group.Reason}");
            foreach (var item in group.Fix?.Details?.Packages.SelectMany(p => p.Unresolved) ?? [])
            {
                md.AppendLine(CultureInfo.InvariantCulture, $"  - unresolved: {item}");
            }
        }

        foreach (var update in notPlanned)
        {
            md.AppendLine(CultureInfo.InvariantCulture, $"- {update.Id} {update.From} → {update.To}: {update.Decision switch
            {
                UpdateDecision.Manual => "needs a manual update",
                UpdateDecision.NeedsTfmUpgrade => "needs a newer target framework",
                _ => "skipped",
            }}{(update.Reason is null ? "" : $" ({update.Reason})")}");
        }

        md.AppendLine();
    }

    private static void AppendStats(StringBuilder md, RunReport report)
    {
        var stats = report.Groups.Select(g => g.Fix?.Stats).OfType<AgentStats>().ToList();
        md.AppendLine("## Run").AppendLine();
        md.AppendLine(CultureInfo.InvariantCulture, $"- Duration: {report.Duration.TotalMinutes:0.0} min");
        md.AppendLine(CultureInfo.InvariantCulture, $"- Groups: {report.Groups.Count(g => g.Status == GroupStatus.Accepted)} accepted, {report.Groups.Count(g => g.Status == GroupStatus.Rejected)} rejected");
        if (stats.Count > 0)
        {
            md.AppendLine(CultureInfo.InvariantCulture, $"- Agent: {stats.Sum(s => s.ModelCalls)} model calls, {stats.Sum(s => s.ToolCalls)} tool calls, " +
                          $"{stats.Sum(s => s.InputTokens) / 1000}k input / {stats.Sum(s => s.OutputTokens) / 1000}k output tokens" +
                          $"{(stats.Sum(s => s.AiCredits) > 0 ? $", {stats.Sum(s => s.AiCredits):0.##} Copilot AI units" : "")}");
        }

        md.AppendLine(CultureInfo.InvariantCulture, $"- Target commit: `{report.TargetCommit.ShortSha()}` · SDK {report.SdkVersion}").AppendLine();
    }
}
